apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-challenge.fullname" . }}
  labels:
    {{- include "devops-challenge.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "devops-challenge.selectorLabels" . | nindent 4 }} 